variable "vsphere_server" {}
variable "vsphere_user" {}
variable "vsphere_password" {}
variable "vsphere_datacenter" {}
variable "vsphere_datastore" {}
variable "vsphere_resource_pool" {}
variable "vsphere_network" {}
variable "vsphere_cluster" {}
variable "k3s_template" {}
variable "k3s_master_mac" {}
variable "k3s_node_1_mac" {}
variable "k3s_node_2_mac" {}
